{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quanly.fullname" . }}-secrets
  labels: {{- include "quanly.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "quanly.databaseUrl" . | quote }}
  REDIS_URL: {{ include "quanly.redisUrl" . | quote }}
  SESSION_SECRET: {{ required "values.secrets.SESSION_SECRET is required" .Values.secrets.SESSION_SECRET | quote }}
{{- range $k, $v := .Values.secrets }}
{{- if and (ne $k "DATABASE_URL") (ne $k "REDIS_URL") (ne $k "SESSION_SECRET") }}
  {{ $k }}: {{ default "" $v | quote }}
{{- end }}
{{- end }}
{{- end }}
